version: '3.7'

services:
  backend:
    build: ./books_exchange
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./books_exchange:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  redis:
    image: redis:5-alpine

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  celery:
    build: ./books_exchange
    command: celery worker --app=books_exchange --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./books_exchange:/usr/src/app
    env_file:
      - ./.env.dev

    depends_on:
      - backend
      - redis

  dashboard:
    build: ./books_exchange
    command: flower -A books_exchange --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev

    depends_on:
      - backend
      - redis
      - celery

volumes:
  postgres_data: